spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crud_db?verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
    username: root
    password: my1WifeAlfa



  jpa:
    hibernate:
      show_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect